spring:
   application:
      name: EUREKA-SERVER
  
 
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#  
#server:
#  port: 8051
  
server:
  # Server port is set to 8761
  port: 8051
  client:
    # Server doesnot required to register it self hence set to false
    registerWithEureka: false
    # Server Does not required to fetch the registry it self
    fetchRegistry: false
    serviceUrl:
      # Server url is set to below
      defaultZone: http://localhost:8051